# -*- coding: utf-8 -*-
"""Hourly Wage Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TtXA5ZtfXr0ZEwNCL1RSti_JqMfeQjT1
"""

#Write your pay program using try and except so that your program handles non-numeric input gracefully
# by printing a message and exiting the program. The following shows two executions of the program:

try: 
    sh = float(input(prompt = 'How many hours did you work this week? '))
    sr = float(input(prompt = 'How much do you make per hour? '))
    fh = float(sh)                             
    fr = float(sr)
    compensation = fh * fr 
    print('''
    Since you worked {:,.2f} hours this week
    and make ${:,.2f} per hour, you made ${:,.2f} this week. 
    Good work!'''.format(sh,
                        sr,
                        compensation))

except: 
    print('Please enter a number. Otherwise the program will not work.')
    quit()

    if fh > 40  : 
      reg = fr * fh
      otp = (fh - 40) * (fr * 0.5)
      xp = reg + otp
else: 
    xp = float(sh) * float(sr)
    print("Pay", xp)